<?php
$title = 'Agregar Usuario';
$this->headTitle($title);
?>

<h1><?php echo  $this->escapeHtml($title);?> </h1>

<?php   
    $form->setAttribute('action',$this->url('crud',['action' => 'add']));
    $form->prepare();
    ?>

    <?php
    echo $this->form()->openTag($form);
    echo $this->formHidden($form->get('id'));
    ?>
<br/>
    <?php
    echo $this->formRow($form->get('nombre'));
    ?>
<br/>
<?php
    echo $this->formRow($form->get('correo'));
    ?>
<br/>
<?php
    echo $this->formRow($form->get('contrasena'));
    ?>
<br/>
      <?php
    echo $this->formSubmit($form->get('submit'));
    ?>